routes:
    /:
        template: home
    # /studio-saas/:
    #     template: home-saas
    /studio-saas/landing-page/:
        template: pack-validation
    /studio-saas/mvp/:
        template: pack-mvp
    /studio-saas/saas/:
        template: pack-saas
    # /agence-shopify/:
    #     template: home-shopify
    # /talent-freelance/:
    #     template: home-talent



collections:

taxonomies:
    tag: /topic/{slug}/
