name: CI Theme
on:
    push:
        branches:
            - develop

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Use PNPM
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.0.2
                  run_install: true
            - name: Build
              run: pnpm run build:prod
            - name: Test
              run: pnpm run test:ci
